---
title: "R Notebook"
output: html_notebook
---
```{r}
#library(RcppCNPy)

source("../doc/feature_ORB_topn.R")

ORB.data <- feature_ORB_topn("/Users/admin/Desktop/Columbia/Spring 2018/Applied DS/Pet Images and Extracted Features - Project 2/python pets", set_name = "n60", nfeatures = 60)

```


# Scratchwork
```{r}
feature_ORB_topn <- function(img_dir, set_name = "", data_name = "pets", export=T, nfeatures = 5) {
  
  library(RcppCNPy)
  
  #py_load_object("/Users/admin/Desktop/Columbia/Spring 2018/Applied DS/GitHub/project-2-predictive-modelling-group-5/doc/py_descriptors.npy")
  #py_run_file("/Users/admin/Desktop/Columbia/Spring 2018/Applied DS/GitHub/project-2-predictive-modelling-group-5/doc/py_ORB_FINAL.py")
  #py_run_file("../lib/py_ORB_FINAL.py")
  
  nfeatures = 60
  img_dir <-  "/Users/admin/Desktop/Columbia/Spring 2018/Applied DS/Pet Images and Extracted Features - Project 2/python pets"
  n_files <- length(list.files(img_dir))-1  
  dat <- data.frame(matrix(NA, nrow = n_files, ncol = 32*nfeatures))
  #dat <- list()
  
  for (i in 1:n_files) {
    #retest <- npyLoad("/Users/admin/Desktop/Columbia/Spring 2018/Applied DS/GitHub/project-2-predictive-modelling-group-5/doc/Printing 2.npy")
     
    # loads i (5,32) top ***5 key pointdescriptors
    # image keypoints
     array <- npyLoad(paste(img_dir,'/', 'pet', i, '.npy', sep = ''))
  
    # turn matrix "array" into a single vector made up of the sequentially 
    # concatonated rows of "subset". assign the new vector to the 
    #ith element of "dat" list
    array <- as.vector(t(array))
    
    if (length(array) == 1920) {
      dat[i,]  <- array
    } else {
      dat[i,]  <- dat[1,]
    }
  }
  
```

